#spring.application.name=company-micro-service
server:
  port: 8081

spring:
  application:
    name: company-micro-service
#  datasource:
#    url: jdbc:h2:mem:test
#  h2:
#    console:
#      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/company
    username: parjunb
    password: parjunb
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: POSTGRESQL

# eureka client
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

debug: true
# zipkin
management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0