#spring.application.name=company-micro-service
server:
  port: 8081

spring:
  application:
    name: company-micro-service
  datasource:
    url: jdbc:h2:mem:test
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update



