#spring.application.name=company-micro-service
server:
  port: 8081

job-service:
  url: http://job:8082
company-service:
  url: http://company:8081
review-service:
  url: http://review:8083

spring:
  application:
    name: company-micro-service
#  datasource:
#    url: jdbc:h2:mem:test
#  h2:
#    console:
#      enabled: true
  datasource:
    url: jdbc:postgresql://postgres_container:5432/company
    username: parjunb
    password: parjunb
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: POSTGRESQL

# RabbitMQ
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest



# eureka client
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://service-registry:8761/eureka/

debug: false
# zipkin
management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

